export const FETCH_BOARDS_REQUESTS = "FETCH_BOARDS_REQUESTS";
export const FETCH_BOARDS_SUCCESS = "FETCH_BOARDS_SUCCESS";
export const FETCH_BOARDS_FAILURE = "FETCH_BOARDS_FAILURE";

export const FETCH_LISTS_REQUESTS = "FETCH_LISTS_REQUESTS";
export const FETCH_LISTS_SUCCESS = "FETCH_LISTS_SUCCESS";
export const FETCH_LISTS_FAILURE = "FETCH_LISTS_FAILURE";

export const FETCH_TASKS_REQUESTS = "FETCH_TASKS_REQUESTS";
export const FETCH_TASKS_SUCCESS = "FETCH_TASKS_SUCCESS";
export const FETCH_TASKS_FAILURE = "FETCH_TASKS_FAILURE";

export const ADD_REQUEST = "ADD_REQUEST";

export const ADD_BOARD = "ADD_BOARD";
export const ADD_COLUMN = "ADD_COLUMN";
export const ADD_TASK = "ADD_TASK";
export const DELETE_TASK = "DELETE_TASK";
export const MARK_AS_COMPLETED = "MARK_AS_COMPLETED";
